### ISSUE TITLE
[Mandatory] Assign Parent Asset

### ISSUE THREAD

**Issue by akshaypuli** [Reveal-IQ/MEMS#34]
[OPTIONAL] Enter Parent Equipment Number.  Valid if equipment is a subcomponent of a larger system. Uses a dropdown input.

**Comment by akshaypuli** [comment]
Tasks to Complete:

- [ ]  Add UI designs
- [ ]  Add Assets to Search API

**Comment by mepoulin** [comment]
MP:  Suggest "Assign Parent Equipment #

**Comment by akshaypuli** [comment]
Reviewed and complete
