### ISSUE TITLE
Table of Medical Equipment

### ISSUE THREAD

**Issue by akshaypuli** [Reveal-IQ/MEMS#80]
![Image](https://user-images.githubusercontent.com/8020014/236655865-4621e7c5-9d62-44df-9501-6c0121e2930a.png)

Table UI is slightly updated, see https://www.figma.com/file/5IfV4SBf28rrnCzAjpnhfU/MEMS-UI?type=design&node-id=0-1&mode=design&t=wMJHmhsQQxUdocZX-0

Includes quantity of each equipment, number of equipment that is active and in-service.

**Comment by mepoulin** [comment]
Suggest adding Equipment Description UMDNS
